### ISSUE TITLE
Redundant token member

### ISSUE THREAD

**Issue by bhattaraiashish** [Imsanskar/Symbolic-Differentiation#1]
https://github.com/Imsanskar/Symbolic-Differentiation/blob/2396a046f1142e4e4fffb67d5058aca6a5484c7c/token.h#L83

No need to store length separately, since string_view will store the length of the string

**Comment by bhattaraiashish** [comment]
More precisely, it is supposed to be here:
https://github.com/Imsanskar/Symbolic-Differentiation/blob/2396a046f1142e4e4fffb67d5058aca6a5484c7c/token.h#L78

**Comment by Imsanskar** [comment]
Thank you for the feedback
